In [2]:
import pandas as pd

In [12]:
pd.read_csv('/Users/ctalamilla/Desktop/DH_DataScience/instaladores/Setup/encuesta_inicial (1).csv', sep=';')

,Nombre del Cuestionario,Apellido y Nombre del Alumno,Email del Alumno,Estado,1. Dirección de correo electrónico:,2. País o ciudad de nacimiento:,3. Género:,4. Fecha de nacimiento (en formato DD/MM/AAAA):,5. ¿Cuál es el máximo nivel educativo que cursás o cursaste?,6. ¿Qué carrera de grado cursás o cursaste?,...,11. ¿Desde qué fecha (DD/MM/AAAA) trabajás en este puesto?,12. ¿Cómo se llama tu ocupación?,"13. ¿Alguna vez (en este trabajo o en otra actividad) trabajaste con&nbsp;datos&nbsp;(recolectando, limpiando, analizando, etc.)?",14. ¿Cuántos años trabajaste con datos?(Si es menos de 1 registrá 0.),15. ¿Cuáles de las siguientes herramientas utilizaste? (indicar todas las utilizadas)- Excel- SPSS- SAS- R- Python- Otras (indicar cúales),16. ¿Alguna vez (en este trabajo o en otra actividad) trabajaste haciendo tareas de programación?,17. ¿Durante cuántos años? (Si no aplica ingresar 0),18. ¿Con qué lenguajes? (Indicar todos los que apliquen)-&nbsp;Python- Ruby- PHP- Java- JavaScript- SQL- C++- Otros (indicar cuáles),19. ¿Qué creés que va a pasar en el curso de Data Science?,20. ¿Qué te gustaría que pase?
0,DSAD - Encuesta de inicio,Macarena Lovagnini,macarenalovagnini@hotmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DSAD - Encuesta de inicio,Lucas Alberto Larese,lucas.larese@outlook.com,Aprobado,lucas.larese@outlook.com,Córdoba - Arg,Masculino,1/11/90,Posgrado,Contador Público,...,1/11/21,Controller,Si,3.0,"Excel, Otras (Power BI)",No,0.0,.,Creo que voy a aprender mucho contenido nuevo ...,Que Argentina salga campeón
2,DSAD - Encuesta de inicio,Beatriz Dávila,betdavila@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DSAD - Encuesta de inicio,Matilde Colman,matildecolman89@gmail.com,Aprobado,matildecolman89@gmail.com,CABA,Mujer,3/4/01,Universitario incompleto,Ciencia Política,...,15/10/21,0,Si,0.0,Excel,No,0.0,0,Aprender a administrar datos,Superar el desafío de enfrentarme a algo nuevo
4,DSAD - Encuesta de inicio,Juan Cruz Cucci,juancruzcucci@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,DSAD - Encuesta de inicio,Isaac Lopez,isaac_torres.21@hotmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,DSAD - Encuesta de inicio,Gabriela Beatriz Mattioli Montaña,gabrielabmattioli@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,DSAD - Encuesta de inicio,Matias Pagano,matias.pagano@outlook.com,Aprobado,matias.pagano@outlook.com,CABA,Masculino,19/4/93,Diplomatura,Lic. en Administración de Recursos Humanos,...,12/7/12,Gerente,Si,1.0,Excel.,NaN,NaN,NaN,NaN,NaN
8,DSAD - Encuesta de inicio,Patricia Viviana Serini,patriciaserini@hotmail.com,Aprobado,patriciaserini@hotmail.com,Argentina,Femenino,29/8/64,Universitario,Ingenieria Civil,...,31/7/21,Ingeniera Civil,No,0.0,Excel,No,0.0,Ninguno,Aprender a trabajar con bases de datos para sa...,Poder hacer trabajis freelance
9,DSAD - Encuesta de inicio,Diego Fonseca,fonsecadiego1996@gmail.com,Aprobado,fonsecadiego1996@gmail.com,Colombia,Masculino,19/1/96,Titulo universitario,Ingenieria Geologica,...,5/7/21,QA Lead,Si,1.0,Excel,No,0.0,NaN,Aprendere a hacer analisis mas detallados con ...,Aprender a manejar informacion con Python en v...
10,DSAD - Encuesta de inicio,Leandro Hernan Vazquez,leovazquez1998@gmail.com,Aprobado,leovazquez1998@gmail.com,Argentina,Masculino,3/3/98,Universitario,Ingenieria Industrial,...,1/3/21,Analista de Datos,Si,3.0,"Excel, Access, SQL, Python, Power BI",Si,2.0,"Python, C++, SQL",Profundizar mas en el analisis de datos,Tener mas conocimiento
11,DSAD - Encuesta de inicio,Gustavo Delmont,gustavodelmont1@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,DSAD - Encuesta de inicio,Tomas Alejandro Duhalde,tomaduhalde@gmail.com,Aprobado,tomaduhalde@gmail.com,Corrientes,Masculino,22/10/98,Universitario,Ingenieria Civil,...,29/11/21,Project Manager,Si,0.0,Excel,No,23.0,NaN,Voy aprender,Aprender
13,DSAD - Encuesta de inicio,Ignacio Ivnisky,ignacioivnisky@hotmail.com,Aprobado,ignacioivnisky@hotmail.com,Argentina,Masculino,15/1/94,Carrera de grado,Licenciatura en Sistemas,...,13/5/14,Analista Impositivo,Si,5.0,"Excel, Power BI, Qlik View, Access",Si,3.0,SQL y Visual Basic,Se van a trabajar herramientas para el análisi...,.
14,DSAD - Encuesta de inicio,Daniel Carrillo,danii23.11@hotmail.com,Aprobado,danii23.11@hotmail.com,"CABA, Argentina",Masculino,23/11/92,Universitario,Ingeniería Industrial,...,1/3/18,Analista de Abastecimiento a Producción,Sí,3.0,Excel,NaN,NaN,NaN,NaN,NaN
15,DSAD - Encuesta de inicio,Alex Bassus,alex.bassus@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,DSAD - Encuesta de inicio,Liam O'Kon,liam.okon@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,DSAD - Encuesta de inicio,HARLEY ANDRES CASTILLO,harleyherrera@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,DSAD - Encuesta de inicio,Agustina Belen Bovalina,agus.bovalina@gmail.com,Aprobado,agus.bovalina@gmail.com,"Ciudad de Buenos Aires, Argentina",Femenino,8/8/95,Universitario finalizado,Licenciatura en Sistemas de la Información de ...,...,18/10/21,Project Manager Officer,Si,4.0,"Excel, SQL Server",Si,1.0,SQL,-,-
19,DSAD - Encuesta de inicio,Carlos Heli,carlosheli@hotmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,DSAD - Encuesta de inicio,BRUNO BELTRAMINI,brunobeltramini@gmail.com,Aprobado,BRUNOBELTRAMINI@GMAIL.COM,"MAR DEL PLATA, ARGENTINA",MASCULINO,15/10/82,UNIVERSITARIO,LIC. EN ECONOMINA,...,11/2/14,ANALISTA,SI,15.0,EXCEL,NaN,NaN,NaN,NaN,NaN
21,DSAD - Encuesta de inicio,Leandro Glossman,lglossman@gmail.com,Aprobado,lglossman@gmail.com,"Argentina, Buenos Aires",Masculino,15/11/83,Universitario,Licenciatura en Sistemas,...,1/2/22,Ingeniero en Software,No,0.0,"Python, Excel",Si,20.0,"Python, Ruby, PHP, Java, JavaScript, SQL",Ni idea,Ni idea
22,DSAD - Encuesta de inicio,Nicolas Suarez,nicolas4acevedo@hotmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,DSAD - Encuesta de inicio,Nicolás Ruiz,npralong92@gmail.com,Aprobado,npralong92@gmail.com,"Argentina, Buenos Aires",Masculino,17/11/92,Actuario en Economía (UBA) - Universitario com...,Actuario en Economía,...,20/07/2017 - 6 años,Data Analyst,"si, actualmente",3.0,"excel, sql y python",trabajo,3.0,sql,voy a aprender mucho sobre python,aprender mucho sobre python
24,DSAD - Encuesta de inicio,Tomas Sarmiento,tommassarmiento@gmail.com,Aprobado,tommassarmiento@gmail.com,buenos aires,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,DSAD - Encuesta de inicio,Laura Viviana Rúa,lauravivianarua@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,DSAD - Encuesta de inicio,Agustin Rutschman,rutschmanagustin@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,DSAD - Encuesta de inicio,Felícitas Sangenis Blazquez,felicitas.sangenisb@gmail.com,Aprobado,felicitas.sangenisb@gmail.com,Argentina,Femenino,24/1/94,UNIVERSITARIO FINALIZADO,niguna,...,1/7/21,Ingeniera industrial,Si,1.0,excel,No,0.0,0,Voy a poder aprender sobre manipulacion de datos,Mejorar mi carrera profesional
28,DSAD - Encuesta de inicio,Alejandro Guerrero,guerrero.alejandro@gmail.com,Aprobado,guerrero.alejandro@gmail.com,Argentina,Masculino,4/12/82,Universitario,Ingeniería en Informática,...,4/7/22,Project Manager,si,7.0,"Excel, Python, Tableau, Business Technology Pl...",si,10.0,"C, C++, Smalltalk, Visual Basic, ABAP, Javascr...",.,.
29,DSAD - Encuesta de inicio,Leonardo Perea,perearcl@gmail.com,Aprobado,perearcl@gmail.com,Argentina,masculino,10/10/87,universidad completa,ingenieria mecanica,...,1/6/17,Ingeniero de Procesos,si,3.0,Excel,no,0.0,-,aprender algo nuevo,que me abra la cabeza
30,DSAD - Encuesta de inicio,Pablo Fernandez,pablofernandez.95@hotmail.com,Aprobado,pablofernandez.95@hotmail.com,Argentina,Masculino,13/7/95,Universitario,Analista de Sistemas,...,5/1/21,SQL Developer,Sí,4.0,Excel,NaN,NaN,NaN,NaN,NaN
31,DSAD - Encuesta de inicio,Victoria Victoria,victoriariso@gmail.com,Aprobado,victoriariso@gmail.com,Ciudad de Buenos Aires,Femenino,24/6/65,maestria en curso,licenciatura en analisis de sistemas/ licencia...,...,1/2/20,me encantaria saberlo,"Si, todo el tiempo",2.0,"Excel, R, Python, SQL",Si,15.0,"R, SQL, y otros que no me acuerdo","Sufrire, aprendere mucho y estare feliz cuando...",animarme a trabajr con eso
32,DSAD - Encuesta de inicio,Nicolas Ezequiel Lepori,nelepori@gmail.com,Aprobado,nelepori@gmail.com,Argentina,Masculino,8/7/92,Master,Contador Publico,...,1/1/22,Manager de operaciones,Si,1.0,Excel,no,0.0,0,Aprender a obtener información en base a la re...,Aprender a utilizar distintas herramientas par...
33,DSAD - Encuesta de inicio,Manuel Rojas,manuel98rojas@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,DSAD - Encuesta de inicio,Federico Paez,fedepaez04@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,DSAD - Encuesta de inicio,Gustavo Mernies,merniesgu@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,DSAD - Encuesta de inicio,Juan Ignacio Landolfi,juanignaciolandolfi@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,DSAD - Encuesta de inicio,Luis Sanchez,luanchezan@gmail.com,Aprobado,luanchezan@gmail.com,Venezuela - Caracas,Masculino,22/7/91,Universitario,Ingenieria de Sistemas,...,2/11/21,Analista de Business Intelligence,SI,2.0,"Excel, Python, SQL",SI,2.0,"Python, PHP, Java, C++, JavaScript",Una exploración y aprendizaje de datos masiva,Que aprenda cosas impresionantes
38,DSAD - Encuesta de inicio,Martin Federico Jaliff,martinjaliff@outlook.es,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,DSAD - Encuesta de inicio,Iván Alberto Zapata,iserranoz35@gmail.com,Aprobado,iserranoz35@gmail.com,"Merída, Yucatán, México",Masculino,25/5/94,Licenciatura,Licenciatura,...,14/1/21,Data Specialist,Sí,2.0,"Python, R, AWS, Tableu",Sí,2.0,"Python, R, SQL",Muchos retos y aprendizaje,Desafíos retadores
40,DSAD - Encuesta de inicio,Maximiliano Zapata,maxzm7@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,DSAD - Encuesta de inicio,Tomás Marseillan,tmarse@outlook.com,Aprobado,tmarse@outlook.com,Estados Unidos,Masculino,20/6/89,Maestría,Economía Empresarial,...,1/9/21,Partner,Si,5.0,Excel,No,0.0,0,Aprender a manejar datos y hacer inferencias d...,Que me divierta mucho
42,DSAD - Encuesta de inicio,Daiana Gamarra,daiana.gamarra.cp@gmail.com,Aprobado,daiana.gamarra.cp@gmail.com,"Buenos Aires,Argentina",femenino,1/6/92,Universitario en Curso,Lic en Biotecnología,...,marzo 2018 aprox,Docente,no,0.0,ninguna,no,0.0,ninguno,voy a aprender mucho,aprender y conocer más sobre la ciencia de datos
43,DSAD - Encuesta de inicio,Nicolás Descalzo,descalzon@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,DSAD - Encuesta de inicio,Valentina Allende,avatonica@gmail.com,Aprobado,avatonica@gmail.com,Argentina,Mujer,5/12/91,Maestria,Sociologia,...,20/7/21,Data Scientist Jr,Si,3.0,"Excel, SPSS, R, Python, SQL, Power BI, Tableau",Si,3.0,"Python, SQL, R",Eso espero,Espero poder consolidar conocimientos y mejora...
45,DSAD - Encuesta de inicio,Diego Uran,urandiego@gmail.com,Aprobado,urandiego@gmail.com,Argentina,Masculino,1/1/78,Universitario,Ingeniería Química,...,1/3/19,Superintendente de Perforación,Sí,0.0,"Excel, PBi",No,0.0,NaN,Enfretntar mis miedos de estudiar nuevamente,Adquirir nuevos conociemineots
46,DSAD - Encuesta de inicio,Lucas Vitantonio,lvitantonio@hotmail.com,Aprobado,lvitantonio@hotmail.com,"Rosario, Santa Fe, Argentina",Masculino,27/9/92,Posgrado,Ingenieria Agronoma,...,1/4/21,Lider e Innovacion,Si,5.0,Excel,NaN,NaN,NaN,NaN,NaN
47,DSAD - Encuesta de inicio,Alan Paolo Gueret,alangueret88@gmail.com,Aprobado,alangueret@gmail.com,Argentina,Masculino,1/11/88,Terciario,Derecho,...,1/1/21,Asesoría,Sí,0.0,Excel,No,0.0,Python,No sé,Aprender
48,DSAD - Encuesta de inicio,Cristian Salinas,salinastalamilla@gmail.com,Aprobado,salinastalamilla@gmail.com,Argentina/Salta,Masculino,5/12/83,Esp. Universitario,Ing Ambiental,...,1/11/21,Superintendente de Medio Ambiente,Si,12.0,"Excel, R, Python",Si,2.0,"Python, JS, SQL",Afianzar conocimientos,Desarrollar modelos objetivos
49,DSAD - Encuesta de inicio,Ana Alonso,ana.alonso@osde.com.ar,Aprobado,ana.alonso@osde.com.ar,Argentina,Femenino,7/10/92,Universitario,Contador Publico Nacional,...,1/7/21,Analista de datos,Si,1.0,Excel,NaN,NaN,NaN,NaN,NaN
50,DSAD - Encuesta de inicio,Juan Zambrano,zambranodazajuanfelipe729@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,DSAD - Encuesta de inicio,Oscar Alonso Ospina Espinosa,oscarospina2515@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,DSAD - Encuesta de inicio,Maximiliano Guillermo Sousa Serro,max_kugai@hotmail.com,Aprobado,max_kugai@hotmail.com,"CABA, Argentina",Masculino,17/9/84,Doctorado,"Biologia, UBA",...,1/5/19,Personal de Apoyo Cientifico Bioinformatico,Si,2.0,"Excel, R, Python, Bash, MySQL",Si,4.0,Python y SQL,Voy a terminar de aprender Machine Learning y ...,Lo que dije antes xD
53,DSAD - Encuesta de inicio,Sigilfredo Ibañez,sigilfredo97@gmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,DSAD - Encuesta de inicio,Fabricio José Palma,dipalmafabricio@gmail.com,Aprobado,dipalmafabricio@gmail.com,"Córdoba, Argentina.",Masculino,13/9/95,Universitario Completo,Licenciado en economía,...,1/6/21,Analista de Business Intelligence,Sí. ETL y análisis de datos.,3.0,Excel,NaN,NaN,NaN,NaN,NaN
55,DSAD - Encuesta de inicio,Agustin Lambertini,arnml@hotmail.com,Sin contestar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN